# Generated by Django 6.0.3 on 2026-03-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField()),
                ('gender', models.CharField(default='N/A', max_length=10)),
                ('city', models.CharField(default='N/A', max_length=50)),
            ],
        ),
    ]
